# Generated by Django 5.1.3 on 2025-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_game_player1_alter_game_player2"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
