# Generated by Django 5.1.3 on 2025-01-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
