# Generated by Django 5.1.3 on 2025-02-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='display_name',
        ),
    ]
