# Generated by Django 5.1.3 on 2025-02-10 10:21

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_customuser_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                null=True,
                upload_to="avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    users.models.validate_file_size,
                ],
            ),
        ),
    ]
