# Generated by Django 5.1.3 on 2025-03-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_customuser_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
