# Generated by Django 5.1.3 on 2025-03-11 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_customuser_last_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="score",
        ),
    ]
