# Generated by Django 5.1.3 on 2025-04-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
