# Generated by Django 5.1.8 on 2025-05-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_customuser_is_anonymized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                max_length=50,
                unique=True,
            ),
        ),
    ]
