# Generated by Django 5.1.3 on 2025-02-08 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(
                related_name="participated_tournaments",
                through="tournaments.TournamentPlayer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
