# Generated by Django 5.1.8 on 2025-05-01 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tournaments",
            "0005_alter_tournament_creator_alter_tournament_winner_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournamentplayer",
            old_name="user",
            new_name="player",
        ),
        migrations.AlterUniqueTogether(
            name="tournamentplayer",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="tournamentplayer",
            name="display_name",
        ),
    ]
