# Generated by Django 5.1.8 on 2025-04-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_creator_alter_tournament_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.DeleteModel(
            name='TournamentPlayer',
        ),
    ]
