# Generated by Django 5.1.8 on 2025-04-29 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_tournament_players_delete_tournamentplayer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='participated_tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
